### ISSUE TITLE
[Bug] New installation in a new macbook giving Eager macro-expansion failure: (wrong-type-argument stringp :lighter)

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#373] opened 2022-10-06 01:51 UTC
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked my private configurations in `custom.el` and `custom-post.el`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

`emacs -Q` does not produce any errors.

`emacs --debug-int` does not give a stack-trace.

error in messages buffer.
```
Eager macro-expansion failure: (wrong-type-argument stringp :lighter) [2 times]
custom-initialize-reset: Wrong type argument: stringp, :lighter
```

Mode-line also does not work as expected 
![image](https://user-images.githubusercontent.com/23665525/194196458-25d80e5a-0864-4c07-b737-e637940f5983.png)

### Steps to reproduce

Clone repo and open emacs app.

### Expected behavior

No error in messages buffer.

Modeline works as expected.

### OS

MacOS

### Emacs Version

28

### Error callstack

```emacs-lisp
error in messages buffer.

Eager macro-expansion failure: (wrong-type-argument stringp :lighter) [2 times]
custom-initialize-reset: Wrong type argument: stringp, :lighter
```
```


### Anything else

_No response_

**Comment by seagle0128** [comment] 2022-10-06 04:12
See https://github.com/Malabarba/aggressive-indent-mode/issues/158. 
The workaround is disabling `aggressive-indent-mode` in `init-edit.el`, or patch `aggressive-indent-mode`: adding docstring while defining the minor mode.

**Comment by seagle0128** [comment] 2022-10-10 01:43
The issue is fixed by upstream.

**Closed by seagle0128** 2022-10-10 01:43 UTC
Labels: bug, wontfix
