### ISSUE TITLE
[Bug] The save icon is displayed incorrectly.

### ISSUE THREAD

**Issue by Hxppdv** [seagle0128/.emacs.d#370] opened 2022-09-06 14:32 UTC
### Thank you for the bug report

- [X] I am using the latest version of `Centaur Emacs`.
- [X] I checked [FAQ](https://github.com/seagle0128/.emacs.d#faq).

### Bug description

The save icon is displayed incorrectly.

### Steps to reproduce

1. Open emacs
2. Open a file
3. Edit the file
4. Check the save icon in the modeline
![image](https://user-images.githubusercontent.com/17672838/188661069-8deb4a85-b408-49ac-94a0-c85fd2770a15.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/17672838/188661353-79d9b63f-45de-4478-aec6-85014d8917ec.png)

### OS

Windows

### Emacs Version

gccemacs-29

### Anything else

This fixes the problem for me, but I don't really know why.
`(set-language-environment "UTF-8")`

**Comment by seagle0128** [comment] 2022-09-06 17:41
It's related to the fonts you installed. What font are you using? And did you installed `all-the-icons` fonts? What else configurations are you using?

**Comment by seagle0128** [comment] 2022-09-07 03:49
Did you install the `symbola` font?

**Comment by Hxppdv** [comment] 2022-09-07 05:06
> Did you install the `symbola` font?

no, i didn't. i'll try it later.

**Comment by Hxppdv** [comment] 2022-09-07 05:06
I found `(set-language-environment "UTF-8")`  reset `charset-priority-list` to make `unicode-bmp` at the beginning of the list.
so I tried `(set-charset-priority 'unicode-bmp)`, and that fixes the problem for me.

**Comment by seagle0128** [comment] 2022-09-07 06:43
Okay. Then I am closing it.

**Closed by seagle0128** 2022-09-07 06:43 UTC
Labels: bug

**Comment by seagle0128** [comment] 2022-09-08 03:55
I could't. And it may be related to 29? Are you able to reproduce with 28?

**Comment by Hxppdv** [comment] 2022-09-08 04:46
> Are you able to reproduce with 28?

Yes, I've tried emacs 28, but the problem is still here.

**Comment by seagle0128** [comment] 2022-09-08 10:17
I  still cannot reproduce. You can add `(set-charset-priority 'unicode-bmp)` into custom.el to address this issue.

**Comment by Hxppdv** [comment] 2022-09-08 16:05
> BTW, I cannot find `charset-priority-list`? How did you check the priorities?

that's a function actually.

I made a minimal reproducible example, you can try this when you have time.
[init.txt](https://github.com/seagle0128/.emacs.d/files/9528482/init.txt)

**Comment by seagle0128** [comment] 2022-09-08 16:15
Thanks! You mean the issue can be reproduced with the attached file? Why adding these configurations?

```elisp
(when (fboundp 'set-charset-priority)
  (set-charset-priority 'unicode))
(prefer-coding-system 'utf-8)
(setq system-time-locale "C")
```

**Comment by Hxppdv** [comment] 2022-09-09 02:55
> Why adding these configurations?

I used `straight.el` to install `doom-modeline` and `all-the-icons`
The rest was copied from your configurations.

> The snippet is to reproduce or fix the issue?

no, I'd tried it, but I couldn't reproduce the problem.

**Comment by seagle0128** [comment] 2022-09-09 03:24
I am confused. The example file is not able to reproduce the issue. What purpose you provide it?

**Comment by Hxppdv** [comment] 2022-09-09 03:59
> I am confused. The example file is not able to reproduce the issue. What purpose you provide it?

:( i was able to reproduce the problem with this example file on MS-windows.

**Comment by seagle0128** [comment] 2022-09-09 04:34
>i was able to reproduce the problem with this example file on MS-windows.

Are you sure? This snippet exists in the example, but you said you could't reproduce the issue with it. Now you can... Did I misunderstand something?

```elisp
(when (fboundp 'set-charset-priority)
  (set-charset-priority 'unicode))
(prefer-coding-system 'utf-8)
(setq system-time-locale "C")
```

<img width="809" alt="image" src="https://user-images.githubusercontent.com/140797/189272426-91516ef2-8f4d-40f8-ab4a-c6765c966237.png">

**Comment by Hxppdv** [comment] 2022-09-09 04:38
> Are you sure? This snippet exists in the example, but you said you could't reproduce the issue with it. Now you can... Did I misunderstand something?
> 
> ```emacs-lisp
> (when (fboundp 'set-charset-priority)
>   (set-charset-priority 'unicode))
> (prefer-coding-system 'utf-8)
> (setq system-time-locale "C")
> ```
I mean without the following font settings there is no problem.

**Comment by seagle0128** [comment] 2022-09-09 04:45
I didn't get it. The `custom.el` is configured by users. You can do anything there to adapt your env.

**Comment by Hxppdv** [comment] 2022-09-09 05:05
> The custom.el is configured by users. You can do anything there to adapt your env.

i know it. but the UTF8 settings and fonts settings are copied from your configurations. these are default settings.
I mean if it is determined that the default settings are indeed causing problems on windows. Maybe you can consider changing the default settings.
I gave as much information as I could, I found that the problem only occurs when you have both UTF8 settings and font settings, so I copied them into an `init.el` file for your testing.
If you are sure that the problem does exist on windows, I think the best way is to change the default UTF8 settings or font settings for windows

**Comment by seagle0128** [comment] 2022-09-09 09:55
I still could't reproduce with the example file you provided. And your information is confusing to me.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/140797/189324143-83ad6737-6305-46f3-8205-37789b5b89d5.png">

**Comment by Hxppdv** [comment] 2022-09-09 10:23
> And your information is confusing to me.

I am confused too. :(
I was even able to reproduce the problem in a virtual machine.
If you can't reproduce my problem, then the information I gave is really confusing and I can understand that. I will keep testing and if I find anything new I will let you know first.

**Comment by seagle0128** [comment] 2022-09-09 10:30
It must be related your local env. In your screenshots, the file icon is also incorrect.

PS: I've added `(set-language-environment "UTF-8")` back.

**Comment by Hxppdv** [comment] 2022-09-09 10:37
> PS: I've added `(set-language-environment "UTF-8")` back.

I saw your latest commit.

I don't actually use your configuration, I just stumbled upon this problem while trying your configuration. : )
> It must be related your local env. In your screenshots, the file icon is also incorrect.

I thought so too, but I was able to reproduce it all inside a freshly installed virtual machine, which made the whole thing very strange.

**Comment by Hxppdv** [comment] 2022-09-09 11:17
> I still could't reproduce with the example file you provided. And your information is confusing to me.

Excuse me, Could you send me the file of this test, please

**Comment by seagle0128** [comment] 2022-09-09 13:43
I load the (example file](https://github.com/seagle0128/.emacs.d/files/9528482/init.txt), and open `init.el` of Centaur Emacs.

**Comment by seagle0128** [comment] 2022-09-10 08:33
`(set-language-environment "UTF-8")` will break color emoji with Emacs 27+ on macOS and Linux. I reverted the commit. If you still experiencing the issue, pls add this to your own `custom.el`.

**Comment by seagle0128** [comment] 2022-09-20 09:03
@Hxppdv Finally I "reproduced" on Windows 11. I don't think it's an issue. The "save" icon of ``Segoe UI Symbol` icon is different from `Symbola` font. If you want to use the old one, just removing unicode settings from `custom.el`, or use `symbola` font as below.

```elisp
(cl-loop for font in '("Symbola" "Symbol" "Segoe UI Symbol")
             when (font-installed-p font)
             return (set-fontset-font t 'unicode font nil 'prepend))
```

**Comment by Hxppdv** [comment] 2022-09-25 14:08
> Finally I "reproduced" on Windows 11.

I'm glad to see that I'm not the only one with this problem, that's enough, thanks.
