### ISSUE TITLE
c++ quick run error when having anaconda

### ISSUE THREAD

**Issue by GeneKao** [seagle0128/.emacs.d#40] opened 2018-11-29 22:50 UTC
Hi, I ran into this problem: when I have ```export PATH="/anaconda3/bin:$PATH"``` in my ```.bash_profile```, I got this error when I pressed f7 to quick run c++ code, but compiling from the terminal is totally fine. It's also totally fine without anaconda, any help would be appreciated. Thanks! 

<img width="796" alt="screenshot 2018-11-29 at 23 39 16" src="https://user-images.githubusercontent.com/1162842/49256719-3f281880-f430-11e8-9c48-6b144d6fdc5c.png">

I am using mac os 10.14.1, .emacs.d release version tag:v4.0.0 and also did the ```brew install cquery```.

**Comment by seagle0128** [comment] 2018-12-01 17:19
Obviously it's caused by your env.  It's a basic lib path searching issue in C++.
First I suggest to use `lsp-python`, since you are using `lsp` + `cquery`.  (BTW, in the latest version, `ccls` replaced `cquery`).
But if you still insist to use `anaconda`, try `export PATH="$PATH; /anaconda3/bin"`.

**Comment by GeneKao** [comment] 2018-12-02 09:55
Thanks for your answer and help @seagle0128 . 

I updated to your latest version and uninstall ```cquery```. I normally run python through the terminal and I need anaconda for scientific packages, so not running c++ using the quick run is fine for me as long as the autocompletion works. 😄 I can live with that. 

How do I add lib/header path for c++ emacs autocompletion in your settings? I noticed that even though it finds anaconda folder first, autocompletion still working fine. I only need autocomplete function for other libraries. (IDE like Xcode, I can put them in the include path search.) 

Thanks for your patient. I am not familiar with elisp but love to use emacs and also for my c++ projects.

**Comment by seagle0128** [comment] 2018-12-02 10:12
Welcome. 

Regarding your C++ header issue, you can refer to https://github.com/MaskRay/ccls/wiki/FAQ#some-cc-headers-are-not-recognized . It's out of scope of Emacs config.

**Comment by seagle0128** [comment] 2018-12-02 10:13
I'd like close it now. Thanks!

**Closed by seagle0128** 2018-12-02 10:13 UTC
Labels: help wanted

**Comment by GeneKao** [comment] 2018-12-03 09:36
@seagle0128 I found the problem for the standard header lib include confusion. 

I installed anaconda through ```brew cask install anaconda```, which somehow installed anaconda in the root directory and export ```PATH="$PATH:/anaconda3/bin"``` never works, so I had to put ```export PATH="/anaconda3/bin:$PATH"``` instead. 

After I reinstall anaconda following the official documentation and put anaconda after ```$PATH``` in my ```.bash_profile``` then everything works fine!

**Comment by seagle0128** [comment] 2018-12-03 10:20
Great to know you've found the root cause!
