### ISSUE TITLE
Adding additional modes

### ISSUE THREAD

**Issue by pcinereus** [seagle0128/.emacs.d#144] opened 2020-01-02 01:14 UTC
I recently came across this emacs 'distribution' and really like it.  I would like to add additional programming models.  In particular, R (ESS).  How involved is this likely to be?  I have a my pre-existing init.el config.  Would also like to impliment poly-r mode...

**Comment by seagle0128** [comment] 2020-01-02 04:12
Glad to know you like it. The PR is welcome. I think you need to implement init-r.el and add it to init.el.

**Comment by atanasj** [comment] 2020-01-31 09:31
My thinking exactly @pcinereus... I look forward to it and happy to test!

**Comment by pcinereus** [comment] 2020-02-01 07:29
I have a very hectic Feb coming up, but am keen to have a go in March.  Will let @atanasj know if I manage to have some success..

**Comment by atanasj** [comment] 2020-02-09 11:04
@seagle0128, I've been testing an `ess-r-mode` config, however in the inferior `R` buffer, some weird things come up (see image).  

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/27214625/74100876-8313c300-4b87-11ea-8b98-bef84b93ea11.png">

It should look like this: 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/74100911-fa495700-4b87-11ea-91dc-7ba51649d044.png">

Can you please let me know how I can resolve it?

**Comment by seagle0128** [comment] 2020-02-09 11:41
@atanasj Try [xterm-color](https://github.com/atomontage/xterm-color)

**Comment by atanasj** [comment] 2020-02-09 12:42
Thanks @seagle0128, that looks great. 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/74102203-5ff01000-4b95-11ea-9eb2-7ede6bc6d33f.png">

However, I think configuring that looks a bit beyond my skill set. Any tips on how I would go about it?

**Comment by seagle0128** [comment] 2020-02-09 13:13
I am not sure which part do you mean. 
Do you mean how to use `xterm-color-filter`?

**Comment by atanasj** [comment] 2020-02-09 13:23
Sorry, I should have been clearer. Yes, how do I get `xterm-color-filter` to parse it… I'm not sure if is due to `ansi` colorizing it, but I was assuming that was the issue. 

It seems from the documentation that `xterm-color-filter` can correct it, but I'm not sure how to add a hook to do that or what needs to happen on the config side. Do you have any pointers? Any help is greatly appreciated.

**Comment by seagle0128** [comment] 2020-02-09 14:57
I took a quick look at ESS. It should be like shis

*NOTE*: Not sure if `font-lock-mode` should be disabled here.

```elisp
(add-hook 'inferior-ess-mode-hook
            (lambda ()
              ;; Disable font-locking in this buffer to improve performance
              (font-lock-mode -1)
              ;; Prevent font-locking from being re-enabled in this buffer
              (make-local-variable 'font-lock-function)
              (setq font-lock-function (lambda (_) nil))
              (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter nil t)))
```

**Comment by atanasj** [comment] 2020-02-09 15:12
Awesome!

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/74104635-b7e54180-4baa-11ea-92b5-ae0aefd5f622.png">

Thanks, that seems to be working well.

**Comment by seagle0128** [comment] 2020-02-09 15:52
No problem!

I committed a patch e631a4fb7c455c93f4491b116a66401f02f2a2b8 to use xterm-color filter in shell and all interpreter buffers.

```elisp
(add-hook 'comint-preoutput-filter-functions 'xterm-color-filter)
```

This should be enough. You don't need any more to enable it in iESS buffer. But please test.

**Comment by atanasj** [comment] 2020-02-09 20:53
Nice, I'll give it a go and feedback.

**Comment by atanasj** [comment] 2020-02-10 02:41
> No problem!
> 
> I committed a patch [e631a4f](https://github.com/seagle0128/.emacs.d/commit/e631a4fb7c455c93f4491b116a66401f02f2a2b8) to use xterm-color filter in shell and all interpreter buffers.
> 
> ```emacs-lisp
> (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter)
> ```
> 
> This should be enough. You don't need any more to enable it in iESS buffer while using `Centaur Emacs`. But please test.
> 
> PS: If you encounter some performance issue, you may need to disable `font-lock-mode`.

@seagle0128, I can confirm that this patch works!

**Comment by atanasj** [comment] 2020-02-17 02:36
@pcinereus, I have been playing with a `ess` config. I have uploaded my `custom-post.org` as a gist. You can find it [here](https://gist.github.com/atanasj/722315bb883018252ca18b1d550385e7) if you're interested.  

It contains a bunch of other config (and is a work in progress), however may be useful to you.

**Comment by pcinereus** [comment] 2020-02-20 00:33
Brilliant, thanks  @atanasj (and @seagle0128).  Currently travelling for work.  Will check it out once I return home next week.

**Comment by snowman** [comment] 2021-01-12 12:22
> Thanks @seagle0128, that looks great.
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/27214625/74102203-5ff01000-4b95-11ea-9eb2-7ede6bc6d33f.png">
> 
> However, I think configuring that looks a bit beyond my skill set. Any tips on how I would go about it?

-----

> Awesome!
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/27214625/74104635-b7e54180-4baa-11ea-92b5-ae0aefd5f622.png">
> 
> Thanks, that seems to be working well.

Sorry to bother @atanasj, but I can't figure out any difference between the two images, so what does `(add-hook 'comint-preoutput-filter-functions 'xterm-color-filter)` really do here?

**Comment by atanasj** [comment] 2021-01-18 02:35
@snowman, I've moved to `doom` for `evil` mode, so I'm a bit rusty re: my memory here, but I think the change that @seagle0128 implemented basically just colorised the `R` console.

**Comment by seagle0128** [comment] 2022-07-05 17:28
Closing it since there is no activity recently.

**Closed by seagle0128** 2022-07-05 17:28 UTC
Labels: enhancement
