### ISSUE TITLE
Emacs crash when opening a JSON file

### ISSUE THREAD

**Issue by cmgustavo** [seagle0128/.emacs.d#72] opened 2019-04-26 15:59 UTC
It happens when I open any .json file. I didn't see any error. How I get more info about this error?

Thanks.

**Comment by seagle0128** [comment] 2019-04-26 17:37
I think you can remove some packages to try. The simple way is comment some lines in `init.el` for troubleshooting. Can you please provide the sample?

**Comment by seagle0128** [comment] 2019-05-09 07:17
Any update, @cmgustavo ? If no, I'd like close it.

**Comment by cmgustavo** [comment] 2019-05-09 13:06
Sorry for delay. It works when comment this line `(require 'init-persp)`, BUT when I open the *.json file and modify the window size, the app closes suddenly.

**Comment by cmgustavo** [comment] 2019-05-09 13:15
Ok, it works if I comments these packages:

```
;(require 'init-highlight)
;(require 'init-persp)
``` 

`init-highlight` makes the app closing when re sizing window. And `init-persp` when opening any *.json file.

Thanks.

**Comment by seagle0128** [comment] 2019-05-09 13:30
I couldn't recreate the issues you described. I tested with a several json files, and all work well. I am using GNU Emacs 26.2 on macOS Mojave. Please update the configurations and retry. If the issue still exists, please provide more details for troubleshooting.

**Comment by cmgustavo** [comment] 2019-05-09 13:52
Seems to be something with a particular JSON file :( all the others work properly. Thanks for your time, I think that was my mistake due to malformed json file.

BTW, I have the same version and Centaur works awesome: ```
GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) ```

**Comment by seagle0128** [comment] 2019-05-09 14:58
Okay. If it's related to the particular JSON file, it may be a issue of `json-mode`, or Emacs itself?

**Comment by cmgustavo** [comment] 2019-05-09 15:24
I don't think so, because it worked on Emacs from scratch on with only json-mode enabled.

**Comment by seagle0128** [comment] 2019-05-09 19:32
So, maybe you should report to `json-mode`?

**Comment by seagle0128** [comment] 2019-05-13 06:37
@cmgustavo I am pretty sure this issue is caused by soma packages in `init-hightlight.el` (while not `init-persp.el`), but I don't know which one. I think you can disable the package in `init-highlight` one by one to check which one cause the crashes.

**Comment by seagle0128** [comment] 2019-05-19 11:10
I am closing it since there is no further update and actions. If you dig out which one cause the issue, please file an issue for that package and reopen it to track.

**Closed by seagle0128** 2019-05-19 11:10 UTC
Labels: question
