### ISSUE TITLE
Installation error [Question]

### ISSUE THREAD

**Issue by romain-pastorelli** [seagle0128/.emacs.d#425] opened 2023-09-21 08:22 UTC
I recently reinstalled Centaur on Emacs 27.1. I really enjoyed my previous version but I needed to re-download it all and I get the following problems :
I) When start it, it shows the following screen
![bug_report](https://github.com/seagle0128/.emacs.d/assets/58110617/e56c4935-35f2-486a-ac2f-84bb412ec336)

II) When I want to close, it asks me "Save desktop y/n :". But 1) whatever I do, it keeps asking me that the next time I close Emacs, 2) I don't know which directory I need to select and 3) it never asked me this before ! I used Centaur for 6 months now and never had problems, and now I re-downloaded it, and nothing works as it should...

**Comment by seagle0128** [comment] 2023-09-21 13:43
1. It looks `tabspaces` returns the error. It's better getting the backtrace. I suggest to `package-refresh-contents` and reinstall `tabspaces`.
2. If you restore the session (press `R` on dashboard) after saving the session to `~/.emacs.d`, you never see the prompt while exiting Emacs. Or just press n to ignore.

**Comment by roman-durajka** [comment] 2023-10-25 10:13
I had the same issue on Ubuntu 22.04 with Emacs version 27.1. Removing 27.1 and installing 29.1 fixed the issue. Reinstalling package `tabspaces` did not resolve the issue help.

I also permanently disabled the prompt asking you to save the desktop by adding `(setq desktop-save nil)` to `cutom.el`.

**Comment by seagle0128** [comment] 2023-10-26 08:09
It seems a compatibility issue of `tabspaces`. In 27.1, `tab-switch` alias is not defined.

See https://github.com/emacs-mirror/emacs/blob/647a9353a35bb6f97a8494f1765400f8a34081ea/lisp/tab-bar.el#L1170 and https://github.com/emacs-mirror/emacs/blob/fda07b56d9e985b6ae74a6845453b55da0345e3c/lisp/tab-bar.el#L2774.

@mclearc Can you please take a look at this?

**Comment by seagle0128** [comment] 2023-10-26 08:17
I submitted a workaround and please test. @roman-durajka @romain-pastorelli

**Comment by roman-durajka** [comment] 2023-10-26 13:31
After updating Centaur using `M-x centaur-update`, the issue no longer persists - now it boots straight into dashboard, as intended. Thanks.

**Comment by mclearc** [comment] 2023-10-26 14:55
> It seems a compatibility issue of `tabspaces`. In 27.1, `tab-switch` alias is not defined.
> 
> See https://github.com/emacs-mirror/emacs/blob/647a9353a35bb6f97a8494f1765400f8a34081ea/lisp/tab-bar.el#L1170 and https://github.com/emacs-mirror/emacs/blob/fda07b56d9e985b6ae74a6845453b55da0345e3c/lisp/tab-bar.el#L2774.
> 
> @mclearc Can you please take a look at this?

fixed by https://github.com/mclear-tools/tabspaces/commit/3ff927ffc427d2debca56bc6ec2cbad37d85dd61

thanks for pointing this out!

**Comment by seagle0128** [comment] 2023-10-27 02:13
Thank you @mclearc !
Closing...

**Closed by seagle0128** 2023-10-27 02:13 UTC
