### ISSUE TITLE
company config in org-mode throwing an error when writing header arguments in code blocks

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/.emacs.d#317] opened 2021-08-12 15:18 UTC
error -
Company: backend (company-capf :with company-yasnippet) error "Args out of range: "ge", 0, 3" with args (candidates get)

company version - 0.9.13
Org mode version 9.4.6 (9.4.6-12-gdcc3a8-elpaplus @ /Users/home/.emacs.d/elpa/org-plus-contrib-20210809/)
emacs version - 28.0.50

**Comment by seagle0128** [comment] 2021-08-14 05:20
I couldn't reproduce. I am afraid not able to address this issue without details and backtrace. It seems an issue of company.

**Comment by CsBigDataHub** [comment] 2021-08-15 03:29
here is the back trace

```error
Debugger entered--Lisp error: (args-out-of-range "env=get-env" 0 12)
  completion-pcm--find-all-completions("env=get-env" #f(compiled-function (string pred action) #<bytecode -0x1a2f1a3fe800e9fb>) #f(compiled-function (f) #<bytecode 0x14e3217146877462>) 11 identity)
  completion-pcm--find-all-completions("env=get-env(" #f(compiled-function (string pred action) #<bytecode -0x1a2f1a3fe800e9fb>) #f(compiled-function (f) #<bytecode 0x14e3217146877462>) 12)
  completion-pcm-all-completions("env=get-env(" #f(compiled-function (string pred action) #<bytecode -0x1a2f1a3fe800e9fb>) #f(compiled-function (f) #<bytecode 0x14e3217146877462>) 12)
  #f(compiled-function (style) #<bytecode -0xcfa65a2ae150c4e>)(partial-completion)
  completion--some(#f(compiled-function (style) #<bytecode -0xcfa65a2ae150c4e>) (basic partial-completion emacs22))
  completion--nth-completion(2 "env=get-env(" #f(compiled-function (string pred action) #<bytecode 0x148fdaaf918da834>) #f(compiled-function (f) #<bytecode 0x14e3217146877462>) 12 (metadata (completion--unquote-requote . t)))
  completion-all-completions("env=get-env(" #f(compiled-function (string pred action) #<bytecode 0x148fdaaf918da834>) #f(compiled-function (f) #<bytecode 0x14e3217146877462>) 12 (metadata (completion--unquote-requote . t)))
  company-capf--candidates("env=get-env(")
  company-capf(candidates "env=get-env(")
  company--multi-backend-adapter-candidates((company-capf company-yasnippet) "env=get-env(" nil)
  company--multi-backend-adapter((company-capf :with company-yasnippet) candidates "env=get-env(")
  apply(company--multi-backend-adapter (company-capf :with company-yasnippet) (candidates "env=get-env("))
  company-call-backend-raw(candidates "env=get-env(")
  company--fetch-candidates("env=get-env(")
  company-calculate-candidates("env=get-env(" nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer schema.org> #<window 121 on schema.org> 231018 4650)
  apply(company-idle-begin (#<buffer schema.org> #<window 121 on schema.org> 231018 4650))
  timer-event-handler([t 24856 35284 637079 nil company-idle-begin (#<buffer schema.org> #<window 121 on schema.org> 231018 4650) nil 0])

```

**Comment by seagle0128** [comment] 2021-08-15 07:51
Thanks! I can reproduce this issue with `emacs -Q`. It's an issue of `company-capf`. Please file an issue for `company`.

**Comment by CsBigDataHub** [comment] 2021-08-15 14:42
thanks, created a error in company repo - https://github.com/company-mode/company-mode/issues/1169

**Comment by dgutov** [comment] 2021-08-15 20:58
@seagle0128 Next time please consider that a problem in some major mode can be a bug in that major mode.

**Comment by seagle0128** [comment] 2021-08-16 07:27
@dgutov Thanks for clarification! There was only company functions according to the backtrace which was provided by @CsBigDataHub . I am not sure if it's the root cause. Definitely will consider more cases.

**Comment by seagle0128** [comment] 2021-08-16 07:28
It's an issue of org-mode. Closing it.

**Closed** 2021-08-16 07:27 UTC

**Comment by dgutov** [comment] 2021-08-16 13:17
@seagle0128 Well, the backtrace ends up in `completion-pcm--find-all-completions`, which is outside of company.

I'll appreciate your help triaging, if next time you see a bug with backtrace which mentions `company-capf`, you suggest the user tries to reproduce the error without company first.
